# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kakao_clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kakao_clone
  pod 'Alamofire', '~> 5.2'

end
